"""Add image_name, image_tag, and digest to DiunUpdate

Revision ID: 1773e6072a71
Revises: 7311ecad9a85
Create Date: 2025-09-06 17:21:21.756310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1773e6072a71'
down_revision: Union[str, Sequence[str], None] = '7311ecad9a85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diun_updates', sa.Column('image_name', sa.String(), nullable=True))
    op.add_column('diun_updates', sa.Column('image_tag', sa.String(), nullable=True))
    op.add_column('diun_updates', sa.Column('digest', sa.String(), nullable=True))
    op.drop_index(op.f('ix_diun_updates_image'), table_name='diun_updates')
    op.create_index(op.f('ix_diun_updates_image_name'), 'diun_updates', ['image_name'], unique=False)
    op.drop_column('diun_updates', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diun_updates', sa.Column('image', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_diun_updates_image_name'), table_name='diun_updates')
    op.create_index(op.f('ix_diun_updates_image'), 'diun_updates', ['image'], unique=False)
    op.drop_column('diun_updates', 'digest')
    op.drop_column('diun_updates', 'image_tag')
    op.drop_column('diun_updates', 'image_name')
    # ### end Alembic commands ###
