"""Create diun_updates table

Revision ID: 7311ecad9a85
Revises: 
Create Date: 2025-09-06 16:11:31.139349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7311ecad9a85'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diun_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('hub_link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diun_updates_hostname'), 'diun_updates', ['hostname'], unique=False)
    op.create_index(op.f('ix_diun_updates_id'), 'diun_updates', ['id'], unique=False)
    op.create_index(op.f('ix_diun_updates_image'), 'diun_updates', ['image'], unique=False)
    op.create_index(op.f('ix_diun_updates_status'), 'diun_updates', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diun_updates_status'), table_name='diun_updates')
    op.drop_index(op.f('ix_diun_updates_image'), table_name='diun_updates')
    op.drop_index(op.f('ix_diun_updates_id'), table_name='diun_updates')
    op.drop_index(op.f('ix_diun_updates_hostname'), table_name='diun_updates')
    op.drop_table('diun_updates')
    # ### end Alembic commands ###
