"""Add image_created_at field to diun_updates table

Revision ID: f62e201ae66b
Revises: 1773e6072a71
Create Date: 2025-09-13 19:43:38.841365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f62e201ae66b'
down_revision: Union[str, Sequence[str], None] = '1773e6072a71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diun_updates', sa.Column('image_created_at', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diun_updates', 'image_created_at')
    # ### end Alembic commands ###
