name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "0.8.17"
        
    - name: Set up Python
      run: uv python install 3.13
      
    - name: Install dependencies
      run: uv sync
      
    - name: Run tests
      run: ./scripts/test.sh